#!/bin/sh

TITLE="Network Manager Service not running after login"

DESCRIPTION="
/etc/nsswitch.conf

@@ -1,9 +1,12 @@
 # Name Service Switch configuration file.
 # See nsswitch.conf(5) for details.
 
-passwd: files mymachines systemd
-group: files mymachines systemd
+# Commented out because of boot problems and NetworkManager failure
+#passwd: files mymachines systemd
+#group: files mymachines systemd
 
+passwd: files mymachines
+group: files mymachines
 shadow: files
 
 publickey: files
"

