#!/bin/sh

source resources/packages

echo -e "Fonts:\n\t${FONTS[*]}"
echo -e "Themes:\n\t${THEMES[*]}"
echo -e "Utils:\n\t${UTILS[*]}"
echo -e "Media:\n\t${MEDIA[*]}"
echo -e "WM:\n\t${WM[*]}"


exit 0
pamac install --as-deps ${FONTS[*]} ${THEMES[*]} ${UTILS[*]} ${MEDIA[*]} ${WM[*]}
