#!/bin/sh

export BASE=$(dirname $0)
DOTS="${BASE}/dots"

cd $BASE


case $1 in
install)
    SRC="./install"
    CMD=( ${@:2} )

    [[ -d $SRC/$2 ]] && \
        CMD=( ${@:3} ) && SRC="$SRC/$2"

    [[ $CMD = "all" ]] && \
        echo "Install all packages from $SRC" && \
        CMD=$(ls $SRC)

    [[ ! $CMD ]] && \
        echo -e "Usage: $(basename $0) install {package name|all|extra}" && \
        ls $SRC && exit 0

    for item in ${CMD[@]}; do
        [[ -d $SRC/$item ]] && continue

        if [[ -x $SRC/$item ]]; then
            echo -e "\033[33m  install: $SRC/$item\033[0m"
            #./$SRC/$item
        else
            echo -e "\033[31mError: package $item not found!\033[0m"
            exit 1
        fi
    done
    ;;

status)
    while IFS=\# read -r item _; do
        item=$(echo $item | sed 's/ *$//g') && [[ ${item} ]] && \
            $BASE/utils/rcopy "$HOME/$item" "$DOTS/$item" simular
    done < $BASE/CONFIGS
    ;;

backup)
    echo -e "-- Copy configs to $DOTS repository --"

    while IFS=\# read -r item _; do
        item=$(echo $item | sed 's/ *$//g') && [[ ${item} ]] && \
            $BASE/utils/rcopy "$HOME/$item" "$DOTS/$item"
    done < $BASE/CONFIGS
    ;;

restore)
    echo -e "-- Copy configs from '$DOTS' repository --"

    while IFS=\# read -r item _; do
        item=$(echo $item | sed 's/ *$//g') && [[ ${item} ]] && \
            $BASE/utils/rcopy "$DOTS/$item" "$HOME/$item"
    done < $BASE/CONFIGS
    ;;

clean)
    echo -e "\033[31m-- Clean $DOTS directory --\033[0m"
    rm -rf $DOTS
    ;;

test)
    while IFS=\# read -r item _; do
        item=$(echo $item | sed 's/ *$//g') && [[ ${item} ]] && echo $item ":"
    done < $BASE/CONFIGS
    ;;

*)
    echo -e "Usage: $(basename $0) {install|status|backup|restore|clean}"
    echo -e "       $(basename $0) install {package name|all|extra} ..."
    ;;

esac
