#!/bin/sh

VERSION=${1:-'2.0.4'}

GITHUB="https://github.com/skanehira/docui/releases/download"
PLATFORM=$(uname -m)
OS=$(uname -s)

URL="${GITHUB}/${VERSION}/docui_${VERSION}_${OS}_${PLATFORM}.tar.gz"

wget -O /tmp/docui.tar.gz $URL && \
    mkdir -p /tmp/docui > /dev/null 2>&1 && \
    tar -C /tmp/docui -xzf /tmp/docui.tar.gz && \
    cp /tmp/docui/docui ~/.local/bin/

rm -rf /tmp/docui*
