#!/bin/sh

MAIN=(
    ".config/bspwm"
    ".config/geany"
    ".config/gtk-3.0"
    ".config/kitty"
    ".config/mc/ini"
    ".config/mpv"
    ".config/polybar"
    ".config/ranger"
    ".config/rofi"
    ".config/sxhkd"
    ".config/systemd"

    ".config/picom.conf"
    ".config/pulsemixer.cfg"

    ".local/share/gtksourceview-3.0"
    ".local/share/xfce4/terminal"

    ".moc/config"
    ".shell"
    ".xrdb"
    ".kbled"

    ".fonts.conf"
    ".vimrc"
    ".Xresources"
    ".xprofile"
    ".xsettingsd"
)

EXTRA=(
    ".fehbg"
    ".zshrc"
)

