#!/bin/sh



UTILS=(
    "xorg-xrandr"
    "xorg-xev"
    "xautomation"
    "xdotool"
    "xsettingsd"            # Provides settings to X11 applications via the XSETTINGS specification
    "numlockx"              # Turns on the numlock key in X11
    "w3m" "mc" "gtop" "tig" "tmux"    
    "grc"                   # Yet another colouriser for beautifying your logfiles or output of commands
    "httpie"                # cURL for humans

    "networkmanager-l2tp"   # L2TP support for NetworkManager

    "kitty"
    "rxvt-unicode"

    "gnome-calculator"      # GNOME Scientific calculator
    "firefox"
    "telegram-desktop"
    "transmission-gtk"
    "seahorse"              # NOME application for managing PGP keys
    "ranger"                # A simple, vim-like file manager
)


MEDIA=(
    "moc-pulse-svn"         # An ncurses console audio player with support for pulseaudio (SVN)
    "mpv"                   # Cross-platform media player
    "feh"                   # Fast and light imlib2-based image viewer
    "scrot"                 # Simple command-line screenshot utility for X
    "evince"                # Document viewer (
                            #   PDF, Postscript, djvu, tiff, dvi, XPS, 
                            #   SyncTex support with gedit, 
                            #   comics books (cbr,cbz,cb7 and cbt)
                            # )
    "pulsemixer"            # CLI and curses mixer for pulseaudio
    "python-mutagen"        # An audio metadata tag reader and writer (python library)
)


