#!/bin/sh

PREINSTALLED=(
    "htop"  "wget" "git" "zsh" "curl"
    "unrar" "p7zip"
    "exfat-utils"
    "imagemagick"           # An image viewing/manipulation program
    "mousepad"              # Simple text editor for Xfce
    "gparted"
)

DEPS=(
)

DEVEL=(
    "ctags"
    "clang"
    "python-pip"

    "gvim"
    "geany"                 # Fast and lightweight IDE
)

FONTS=(
    "terminus-font"
    "ttf-font-awesome"
    "ttf-iosevka-fixed-curly"
    "ttf-polybar-icons"
    "ttf-symbola"
    "ttf-symbola-infinality"
    "ttf-ubuntu-font-family"
)

THEMES=(
    "adapta-gtk-theme"
    "papirus-icon-theme"
)

UTILS=(
    "xorg-xrandr"
    "xorg-xev"
    "xautomation"
    "w3m" "mc" "gtop" "tig" "tmux"    
    "grc"                   # Yet another colouriser for beautifying your logfiles or output of commands
    "httpie"                # cURL for humans

    "networkmanager-l2tp"   # L2TP support for NetworkManager

    "kitty"
    "rxvt-unicode"

    "gnome-calculator"      # GNOME Scientific calculator
    "firefox"
    "telegram-desktop"
    "transmission-gtk"
    "seahorse"              # NOME application for managing PGP keys
    "ranger"                # A simple, vim-like file manager
)


MEDIA=(
    "moc-pulse-svn"         # An ncurses console audio player with support for pulseaudio (SVN)
    "mpv"                   # Cross-platform media player
    "feh"                   # Fast and light imlib2-based image viewer
    "scrot"                 # Simple command-line screenshot utility for X
    "evince"                # Document viewer (
                            #   PDF, Postscript, djvu, tiff, dvi, XPS, 
                            #   SyncTex support with gedit, 
                            #   comics books (cbr,cbz,cb7 and cbt)
                            # )
    "pulsemixer"            # CLI and curses mixer for pulseaudio
)

WM=(
    "xsettingsd"            # Provides settings to X11 applications via the XSETTINGS specification
    "picom-ibhagwan-git"    # iBhagwan's compton|picom fork (X compositor) with dual_kawase blur and rounded corners
    "sxhkd"                 # Simple X hotkey daemon
    "rofi"                  # A window switcher, run dialog and dmenu replacement
    "polybar"               # A fast and easy-to-use status bar
    "numlockx"              # Turns on the numlock key in X11
    "bspwm"                 # Tiling window manager based on binary space partitioning
)

EXTRA=(
    "g810-led-git"          # Linux led controller for Logitech G213, G410, G413, 
                            # G512, G513, G610, G810, G815, G910 and GPRO Keyboards
)


REMOVE_PKGS=(
    "midori"    # Lightweight web browser
    "parole"    # Modern media player based on the GStreamer framework
    "qpdfview"  # A tabbed PDF viewer using the poppler library
)
