#!/bin/sh

BASE=$(realpath "$(dirname $0)")
PROFILE=${1:-$USER}
HOSTNAME=${2:-$(hostname)}

if [[ ! -d $PROFILE ]]; then
    PROFILE="/home/$PROFILE"

    [[ ! -d $PROFILE ]] && \
        echo "Not found profile" && exit 1
fi

DATE=( $(date +'%F %H%M%S') )
DEST="$BASE/__backup__/${DATE[0]}/$(basename $PROFILE)@$HOSTNAME:${DATE[1]}"

mkdir -p $DEST

