#!/bin/sh

PKGS=(
    "w3m"
    "httpie"                # cURL for humans
    "firefox"
    "telegram-desktop"
    "transmission-gtk"
)


echo -e "\033[32m-- Install Network packages from AUR --\033[0m"
echo -e "Packages:\n\t${PKGS[@]}"

pamac install ${PKGS[@]}
