#!/bin/sh

BASE=$(realpath "$(dirname $0)/../")
DOTS="${BASE}/dots"

CONFIGS=(
    ".vimrc"
    ".vim/colors"
    ".vim/autoload/airline/themes"
)

PKGS=(
    "gvim"
)

sudo pacman -S ${PKGS[@]}

rm -rf $HOME/.vim/

for item in ${CONFIGS[@]}; do
    ./utils/rcopy "$DOTS/$item" "$HOME/$item"
done

mkdir -p $HOME/.vim/bundle/
# Install vundle plugin manager from git...
git clone https://github.com/VundleVim/Vundle.vim.git \
    $HOME/.vim/bundle/Vundle.vim

vim --not-a-term +PluginInstall +qall
