#!/bin/sh

BASE=$(realpath "$(dirname $0)/../")
DOTS="${BASE}/dots"

LIST=(
    ".vimrc"
    ".vim/colors"
    ".vim/autoload/airline/themes"
)


sudo pacman -S gvim

cd $BASE
rm -rf $HOME/.vim/
mkdir -p $HOME/.vim/bundle/

for item in ${LIST[@]}; do
    ./utils/rcopy "${DOTS}/${item}" "${HOME}/${item}"
done

# Install vundle plugin manager from git...
git clone https://github.com/VundleVim/Vundle.vim.git \
    $HOME/.vim/bundle/Vundle.vim

vim --not-a-term +PluginInstall +qall
