#!/bin/sh

BASE=$(realpath "$(dirname $0)/../")
DOTS="$BASE/dots"

PACKAGES=(
    "picom-ibhagwan-git"    # iBhagwan's compton|picom fork (X compositor) with dual_kawase blur and rounded corners
    "sxhkd"                 # Simple X hotkey daemon
    "rofi"                  # A window switcher, run dialog and dmenu replacement
    "polybar"               # A fast and easy-to-use status bar
    "dunst"                 # Customizable and lightweight notification-daemon
    "bspwm"                 # Tiling window manager based on binary space partitioning
)
