#!/bin/sh

TITLE="Main title of packet"

DESCRIPTION="
    Text description from packet
"

DEPENDENCIES=(
    # List of packet dependencies (any packets)
)

PACKAGES=(
    # List of packages to be installed
)

CONFIGS=(
    # List of configs files
)

pre_install() {
    echo "Script executed before the package installation process"
}

pre_config() {
    echo "Script executed before the process of transferring configuration files"
}

install() {
    echo "Script executed at the end of the packages installation process"
}

