#!/bin/sh

TITLE="Base development packages"

PACKAGES=(
    "git"
    "ctags"
    "clang"
    "python-pip"
    "libpqxx"
)

pre_install() {
    echo -e "\033[33m  - Install base development meta-package\033[0m"
    sudo pacman -S base-devel
}
