#!/bin/sh

TITLE="Icons-themes from AUR"

PACKAGES=(
    "papirus-icon-theme"
    "papirus-folders" # https://github.com/PapirusDevelopmentTeam/papirus-folders
                      # papirus-folders -C yaru --theme Papirus
)

install() {
    # Set papirus folders icon-theme variant
    papirus-folders -C ${PAPIRUS_FOLDERS:-yaru} --theme Papirus
}
