#!/bin/sh

TITLE="Network packages"

PACKAGES=(
    "wget"
    "curl"
    "w3m"
    "httpie"                # cURL for humans
    "sshfs"
    "firefox"
    "telegram-desktop"
    "transmission-gtk"
)

echo "net"
