#!/bin/sh

TITLE="Utils packages"

PACKAGES=(
    "xorg-xrandr"
    "xorg-xev"
    "xautomation"
    "xdotool"
    "xsettingsd"            # Provides settings to X11 applications via the XSETTINGS specification
    "numlockx"              # Turns on the numlock key in X11
    "exfat-utils"
    "htop"
    "zsh"
    "unrar"
    "p7zip"
    "mc"
    "gtop"
    "tig"
    "tmux"    
    "grc"                   # Yet another colouriser for beautifying your logfiles or output of commands

    "rxvt-unicode"

    "gnome-calculator"      # GNOME Scientific calculator
    "seahorse"              # NOME application for managing PGP keys

    "ranger"                # A simple, vim-like file manager
    "trash-cli"             # Command line trashcan (recycle bin) interface
    "ncdu"                  # Disk usage analyzer with an ncurses interface
    "imagemagick"           # An image viewing/manipulation program
    "mousepad"              # Simple text editor for Xfce
    "gparted"
)
