#!/bin/sh

TITLE="VIM and environment"

CONFIGS=(
    ".vimrc"
    ".vim/colors"
    ".vim/autoload/airline/themes"
)

PACKAGES=(
    "gvim"
)

pre_config() {
    echo ""
    #rm -rf $HOME/.vim/
}

post_install() {
    echo ""
    #mkdir -p $HOME/.vim/bundle/
    ## Install vundle plugin manager from git...
    #git clone https://github.com/VundleVim/Vundle.vim.git \
        #$HOME/.vim/bundle/Vundle.vim

    #vim --not-a-term +PluginInstall +qall
}
