#!/bin/sh

TITLE="VIM and environment"

CONFIGS=(
    ".vimrc"
    ".vim/colors"
    ".vim/autoload/airline/themes"
)

PACKAGES=(
    "gvim"
)

pre_config() {
    echo -e "\t- Remove previous configuration..."
    rm -rf $HOME/.vim/
}

install() {
    echo -e "\t- Install Vundle plugin manager from git..."
    mkdir -p $HOME/.vim/bundle/
    git clone https://github.com/VundleVim/Vundle.vim.git \
        $HOME/.vim/bundle/Vundle.vim

    echo -e "\t- Install vim plugins..."
    vim --not-a-term +PluginInstall +qall
}
