#! /bin/sh

###################
## configuration ##
###################

bspc monitor -d ● ● ● ● ● ● ● ● ● ●

bspc config border_width        2
bspc config window_gap          16
bspc config split_ratio         0.52

## color settings
bspc config focused_border_color  "#BF616A"
bspc config normal_border_color   "#2E3440"
bspc config presel_feedback_color "#A65D6A"

##################
## window rules ##
##################

bspc rule -a feh state=floating follow=on center=on
bspc rule -a mpv state=floating follow=on center=on
bspc rule -a URxvt state=floating follow=on
bspc rule -a Gnome-calculator state=floating follow=on center=on
bspc rule -a TelegramDesktop state=floating follow=on
bspc rule -a Transmission-gtk state=floating follow=on
bspc rule -a Pamac-manager state=floating follow=on center=on

# don't manage conky
bspc rule -a Conky state=floating manage=off

###############
## autostart ##
###############
pkill sxhkd
sxhkd &

light-locker &

## set the wallpaper
~/.fehbg

## Applets ##
nm-applet &
xfce4-power-manager &
blueman-applet &
pamac-tray &
/usr/lib/xfce4/notifyd/xfce4-notifyd &

## Polybar panel
export MONITOR=$(xrandr | grep " connected " | awk '{print $1}')

pkill polybar
polybar top &
polybar layouts &
polybar tray &

# compoze manager
pkill picom
LC_ALL=C picom -b
