#! /bin/sh

###################
## configuration ##
###################

bspc monitor -d ● ● ● ● ● ● ● ● ● ●

bspc config border_width        2
bspc config window_gap          16
bspc config split_ratio         0.52

## color settings
bspc config focused_border_color  "#bf616a"
bspc config normal_border_color   "#2e3440"
bspc config presel_feedback_color "#2e3440"

##################
## window rules ##
##################

bspc rule -a feh state=floating follow=on center=on
bspc rule -a mpv state=floating follow=on center=on
bspc rule -a URxvt state=floating follow=on
bspc rule -a Gnome-calculator state=floating follow=on center=on
bspc rule -a TelegramDesktop state=floating follow=on
bspc rule -a Transmission-gtk state=floating follow=on
bspc rule -a Pamac-manager state=floating follow=on center=on

# don't manage conky
bspc rule -a Conky state=floating manage=off

###############
## autostart ##
###############

## Applets ##
nm-applet &
xfce4-power-manager &
blueman-applet &
pamac-tray &

## Polybar panel
export MONITOR=$(xrandr | grep " connected " | awk '{print $1}')

pkill polybar
polybar top &
polybar layouts &
polybar tray &

