#!/bin/sh
#
# Linux led controller for Logitech G213, G410, G413, 
# G512, G513, G610, G810, G815, G910 and GPRO Keyboards
# https://github.com/MatMoul/g810-led
#

TITLE="Install Linux led controller for Logitech from AUR"

PACKAGES=(
    "g810-led-git"
)

CONFIGS=(
    # List of configs files
    ".kbled"
)
