#!/bin/sh
#
# NetworkManager-l2tp is a VPN plugin for NetworkManager which provides 
# support for L2TP and L2TP/IPsec (i.e. L2TP over IPsec) connections.
# https://github.com/nm-l2tp/NetworkManager-l2tp
#

TITLE="NetworkManager-l2tp package from AUR"

PACKAGES=(
    "xl2tpd"
    "networkmanager-l2tp"   # L2TP support for NetworkManager
)
