#!/bin/sh

TITLE="Remove preinstalled packages"

REMOVED=(
    "midori"    # Lightweight web browser
    "parole"    # Modern media player based on the GStreamer framework
    "qpdfview"  # A tabbed PDF viewer using the poppler library
)

install() {
    pamac remove ${REMOVED[@]}
}
