#!/bin/sh

TITLE="Activate SSH-Agent service"

CONFIGS=(
    ".config/systemd/user/ssh-agent.service"
)

install() {
    systemctl --user daemon-reload
    systemctl --user enable ssh-agent
    systemctl --user restart ssh-agent

    systemctl --user status ssh-agent
}
