#!/bin/sh

BASE=$(realpath "$(dirname $0)/../../")
DOTS="$BASE/dots"

SERVICE=".config/systemd/user/ssh-agent.service"


echo -e "\033[32m-- Activate SSH-Agent service --\033[0m"

$BASE/utils/rcopy "$DOTS/$SERVICE" "$HOME/$SERVICE"

systemctl --user daemon-reload
systemctl --user enable ssh-agent
systemctl --user restart ssh-agent

systemctl --user status ssh-agent
