#!/bin/sh

TITLE="Test package"

CONFIGS=(
    .vimrc
    .vim/colors
    .vim/autoload/airline/themes
)

PACKAGES=(
    "ctags"
    "clang"
    "python-pip"
    "libpqxx"
)

post_install() {
    echo "Post install script"
}

