#!/bin/sh

TITLE="Test package"

DESCRIPTION="
    This is line one.
    This is line two.
    This is line three.
"

CONFIGS=(
    .vimrc
    .vim/colors
    .vim/autoload/airline/themes
)

PACKAGES=(
    "ctags"
    "clang"
    "python-pip"
    "libpqxx"
)

install() {
    echo "Post install script"
}

